### ISSUE TITLE
Script no longer works if $XDG_CONFIG_HOME is unset

### ISSUE THREAD

**Issue by arbyste** [Ajatt-Tools/ames#11]
I noticed that you recently added a section to make the script $XDG_CONFIG_HOME compliant, which is great, however because you use the `set -u` option at the top, it now causes an error to be thrown at line 35 if $XDG_CONFIG_HOME isn't defined, since you're trying to set an empty variable.

I could submit a pull request that removes the -u option from set, but I presume that you want to check for unset variables elsewhere in the script, so I'm not really sure what the best way to handle this is.

**Comment by arbyste** [comment]
Actually never mind, I figured it out. The fix is in https://github.com/eshrh/ames/pull/12

**Comment by stephen-huan** [comment]
Thanks for the fix! I merged it now.

> I could submit a pull request that removes the -u option from set, but I presume that you want to check for unset variables elsewhere in the script, so I'm not really sure what the best way to handle this is.

Just for my future reference, a generic way to do this would be the guard pattern

```bash
set +u
local config_dir="$XDG_CONFIG_HOME"
set -u
```

which is easier to use for ignoring unset variables in long blocks of code but is only valid if the script started with `set -u` in the first place. I'll try to upstream your fix to <https://xdgbasedirectoryspecification.com/> (where I got the snippet from).
