### ISSUE TITLE
Can't install with pipewire-pulse on Arch (aur)

### ISSUE THREAD

**Issue by WilsonNet** [Ajatt-Tools/ames#13]
I have using ames for more than a year and it always worked fine with pipewire-pulse. Today I went to update my arch installation and I couldn't because ames requirement for `pulseaudio`  was conflicting with `pipewire-pulse`.

Which is weird because `pipewire-pulse` should be a perfect replacement for `pulseaudio`. (At leas it is what the videos on youtube told me).

So, I uninstalled ames, tried to install again, and this is the error that I got.

resolving dependencies...
looking for conflicting packages...

```
:: pulseaudio-17.0-3 and pipewire-pulse-1:1.2.2-1 are in conflict. Remove pipewire-pulse? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: pulseaudio-17.0-3 and pipewire-pulse-1:1.2.2-1 are in conflict
```

Looking at the PKGBUILD I noticed that it is like this

```
depends=('pulseaudio' 'ffmpeg' 'maim' 'xdotool' 'libnotify' 'xclip')
```

I imagine if there is a way to do something like

``` 
depends=(('pulseaudio' | 'pipewire-pulse) 'ffmpeg' 'maim' 'xdotool' 'libnotify' 'xclip')
```

Would solve the issue

**Comment by WilsonNet** [comment]
It seems like someone already solved the issue and the AUR mantainer is aware

https://aur.archlinux.org/packages/ames#comment-984979

**Comment by eshrh** [comment]
fixed! (the aur maintainer is me)
