### ISSUE TITLE
Sigterm not killing ffmpeg

### ISSUE THREAD

**Issue by WilsonNet** [Ajatt-Tools/ames#14]
I'm using ames (in a local copy) and it suddenly have stopped working the audio capture (don't know exactly when because I haven't capture audio in months)

After some debugging I realized that the line that was getting stuck is 

```
    while [ "$(du "$audio_file" | awk '{ print $1 }')" -eq 0 ]; do
        true
    done
```
and looking at the `/tmp` folder realized that all the files there had 0 bytes.

Searched in the moe way discord for `ames` and saw someone saying that they were having problems with ames sigkill not killing ffmpeg and voila, btop had plenty of ffmpeg instances opened, after closing them the audio was captured.

Gonna look further more another day, that is all the info I have for now 

**Environment Info:**
Distro Arch
WM - Awesome
Using a local copy of ames inside the `bin` directory 
Pipewire with pipewire-pulse

**Comment by eshrh** [comment]
Hi! I'm not really sure why this is happening and I can't reproduce it at the moment. I'll look into trying to reproduce this properly in 1-2 weeks when I have some time again. 

I'll of course accept a PR if it works for you, and I'd be happy to add you as a collaborator if the patch seems like the type of code that might need maintenance in the future.

This goes for anyone else reading this as well; if you've submitted a PR, currently use ames, and would like push access, please send me an email! (esrh at esrh.me)

**Comment by WilsonNet** [comment]
It is working now. There are two issues

So, the issue is that for some reason the sigterm > save data is very slow right now
It used to work perfectly, I don't know what happened but it is an environment issue.

And even after the sigterm and the audio has been recorded, it does not closes ffmpeg completly, so I added a `kill -9` after the while (and removed the backup that was not being used anywhere)

This is how my function looks like

```
record_end() {
    local -r audio_file="$(sed -n "1p" "$recording_toggle")"
    local -r pid="$(sed -n "2p" "$recording_toggle")"
    local -r start_time="$(sed -n "3p" "$recording_toggle")"
    local -r duration="$(($(current_time) - start_time))"

    echo "The pid is: ${pid}"
    if [ "$duration" -le "$MINIMUM_DURATION" ]; then
        sleep "$((MINIMUM_DURATION - duration))e-3"
    fi

    rm "$recording_toggle"
    kill -15 "$pid"

    while [ "$(du "$audio_file" | awk '{ print $1 }')" -eq 0 ]; do
        true
    done

    kill -9 "$pid"

    store_file "${audio_file}"
    update_sound "$(basename -- "$audio_file")"

    notify_record_stop
}
``` 

Guess I need to figure out why this record is so sow after the sigterm is triggered, but that is an environment issue, so I won't open a PR.

**Comment by WilsonNet** [comment]
One more update:
I gave up trying to make `ffmpeg` work and discovered that you can use pipewire to record audio

That way I could get a very precise audio from where I pressed the `sigterm` command, 

`pw-record -P '{ stream.capture.sink=true }' test.opus` (I don't even know if it encodes properly to opus but it worked anyway)

I'm not making cards right now, so I haven't adapted the script, but this is an escape hatch if anyone else needed it

**Comment by stephen-huan** [comment]
Thanks for the detailed investigation! I also [found](https://github.com/eshrh/ames/blob/master/contrib/python/README.md#recording-audio) that ffmpeg was quite buggy when recording audio, so I wrote [python](https://github.com/eshrh/ames/blob/master/contrib/python/src/audio-record) and [cython](https://github.com/eshrh/ames/tree/master/contrib/cython) scripts wrapping portaudio but never got around to packaging this in an ergonomic way. 

I didn't know pipewire had a recording functionality. If you're so inclined, feel free to send a PR adding a [contrib](https://github.com/eshrh/ames/tree/master/contrib) configuration. Otherwise, I'll try to get around to it eventually. We might try to use pipewire if we detect it and fallback to pulse if isn't available, so that ames works out of the box. The audio glitches have been an issue for too long.

**Comment by emiham** [comment]
I was able to solve this by removing the `-nostdin` flag. It *seems* to work without any issues, but I also don't know why it was there in the first place.
